# Generated by Django 2.2.3 on 2019-07-03 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maraichage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legum1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_plantation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nbr_plant', models.IntegerField(default=0)),
                ('poid_recolte', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200)),
                ('date_recolte', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Legum2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
