# Generated by Django 2.2.3 on 2019-07-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesouscription', models.DateField()),
                ('dateexpiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('prix', models.IntegerField()),
                ('abonnement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateachat', models.DateField()),
                ('prixachat', models.IntegerField()),
                ('etat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Statu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('competance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAdhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('prix', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('adhesionuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlieu.Adhesion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlieu.Statu')),
            ],
        ),
        migrations.CreateModel(
            name='Machineoutil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('occupe', models.BooleanField()),
                ('couthoraire', models.IntegerField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlieu.Maintenance')),
            ],
        ),
        migrations.AddField(
            model_name='adhesion',
            name='adhesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlieu.TypeAdhesion'),
        ),
    ]
