# Generated by Django 2.2.3 on 2019-07-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierlieu', '0002_auto_20190717_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adhesionuser',
            new_name='adhesion',
        ),
    ]
